import * as React from 'react';
import Head from 'next/head';
import dynamic from 'next/dynamic';

const Main = dynamic(() => import('./index'), {
  ssr: false,
});

function MyApp() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link href='https://fonts.googleapis.com/css?family=Roboto&display=optional' rel='stylesheet' type='text/css'/>
        <link rel="icon" href="/favicon.ico"/>
        <title>meninovnik</title>
      </Head>
      <Main />
    </>
  );
}

export default MyApp;
